ask_dunin/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ask_dunin.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^hello/$', 'requests.views.hello', name='hello'),
	url(r'^$', 'ask.views.index'),
	url(r'^registration/signup$', 'ask.views.register'),
	url(r'^profile$', 'ask.views.profile'),
	url(r'^login$', 'django.contrib.auth.views.login', {'redirect_field_name': '/question'}),
	url(r'^logout$', 'django.contrib.auth.views.logout'),
	url(r'^question$', 'ask.views.question'),
	url(r'^tag$', 'ask.views.tag'),
	url(r'^like$', 'ask.views.like'),
	url(r'^rightanswer$', 'ask.views.rightanswer'),
	url(r'^ask_question$', 'ask.views.ask_question'),

)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ask/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(User)
	rating = models.IntegerField(default=0)
	avatar_url = models.CharField(max_length=60)
	avatar = models.ImageField(upload_to='', default='nopic.jpg')

class Question(models.Model):
	author = models.ForeignKey(Profile)
	title = models.CharField(max_length=60)
	text = models.TextField()
	rating = models.IntegerField(default=0)
	date_added = models.DateTimeField(auto_now_add=True)

class Answer(models.Model):
	author = models.ForeignKey(Profile)
	question = models.ForeignKey(Question)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	rating = models.IntegerField(default=0)
	is_right = models.BooleanField(default=False)

class Tag(models.Model):
	tag_word = models.CharField(max_length=60)
	questions = models.ManyToManyField(Question) 

class QuestionVote(models.Model):
	vote = models.IntegerField(default=0)
	user = models.ForeignKey(User)
	question = models.ForeignKey(Question)

class AnswerVote(models.Model):
	vote = models.IntegerField(default=0)
	user = models.ForeignKey(User)
	answer = models.ForeignKey(Answer)

templates/ask_question.html
{% extends "base.html" %}

{% block content %}
<h2>New question</h2>
<br>	
<form method="POST" action="/ask_question">
	{% csrf_token %}
{% for field in form %}
	<div class="row">
		<div class="span2">
			<label for="{{ field.id_for_label }}">{{ field.label }}</label>
		</div>
		<div class="span5">
			{% if field.name == "title" %}
			<input style="resize: none; width: 100%;" autocomplete="off"
			id="{{ field.id_for_label }}" name="{{ field.name }}" type="text" 
			value="{{ field.value|default_if_none:"" }}"/>	
			{% elif field.name == "text" %}
			<textarea style="resize: none; width: 100%; height: 300px" 
			id="{{ field.id_for_label }}" name="{{ field.name }}" type="text" 
			value="{{ field.value|default_if_none:"" }}" ></textarea>	
			{% elif field.name == "tags" %}	
			<input style="resize: none; width: 100%;" name = "{{ field.name }}"type="text" 
			value="{{ field.value|default_if_none:"" }}"/>		
			{% endif %}
		</div>
	</div>
	{% if field.errors %}
		<div class="row">
			<div class="span2 offset2 alert alert-error"> 
				{{field.errors}}
			</div>
		</div>		
	{% endif %}

{% endfor %}
	<div class="row">
		<div class="span5 offset2">
				<input type="hidden" name="next" value="{{ next }}"/>
				<button type="submit" class="btn btn-info">Ask!</button>
		</div>
	</div>
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head> 
	{% load staticfiles %}
	{% load custom_tags %}	
	<meta content="text/html"/>
	<link rel="stylesheet" type="text/css" href = "{% static 'bootstrap/css/bootstrap.css' %}" />
	<link rel="stylesheet" type="text/css" href = "{% static 'my.css' %}" />
</head>

<body>
		<div class="container">
    		<div class="row">
				<div class = "navbar">
					<div class = "navbar-inner">
						<div class = "container">
							<a class = "brand" href="/"> AskMe </a>
							<form class="navbar-search pull-left">
								<input type="text" class="search-query" placeholder="Search">
							</form>									
							<ul class="nav pull-right">
								{% if user.is_authenticated %}
								<li><img class = "img-rounded" style = "margin: 5px" src="{{user.profile.avatar.url}}" heigth="30" width="30" alt=""/></li>								
								<li> <p class="nav navbar-text" style="font-size: 12pt">{{user.username}}</p> </li> 
								{% endif %}		
								<li class="divider-vertical"></li>	
								{% if user.is_authenticated %}
								<li> <a href="/profile">Settings</a> </li>
								<li> <a href="/logout">Log out</a> </li>
								{% else %}		
				 				<li> <a href="/login">Log in</a> </li>
				 				<li> <a href="/registration/signup">Sign up</a> </li>
				 				{% endif %}
								<li style="display: none"> <a href="#">Register</a> </li>
							</ul>
							{% if user.is_authenticated %}
							<a href="/ask_question" class="btn btn-primary pull-right">ASK!</a>	
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>

	<div class="container">
		<div class="row">
			<div class="span8">
			{% block content %}{% endblock %}
			</div>		
			<div class="span3 offset1">
				<div>
					{% get_popular_tags %}
					<!--
						<h2>Popular Tags</h2>
						<p>
							perl <span class="tag1">python</span> TechnoPark <br> <br>
							<span class="tag2">MySQL</span> <span class="tag3">django</span> <br> <br>
							Mail.ru Voloshin <span class="tag4">Firefox</span> 
						</p>
					!-->
				</div>
				<div>		
					{% get_best_members %} 
					<!--
					<h2>Best Members</h2>			
					<ul style="list-style:none">			
						<li> <a>Bob Dylan</a> </li>
						<li> <a>Neil Young</a> </li>
						<li> <a>Johnny Cash</a> </li>
						<li> <a>Tom Waits</a> </li>
					</ul>
					!-->
				</div>
			</div>		
		</div>
	</div>

<script type="text/javascript" src="{% static "jquery.js" %}"> </script>
{% block foot %}
{% endblock %}
</body>
</html>

templates/best_members.html
<h2>Best Members</h2>			
<ul style="list-style:none">	
{% for member in members %}
<li>{{member.username}}</li>
{% endfor %}
</ul>

templates/index.html
{% extends "base.html" %}


{% block content %}
	{% load staticfiles %}
	{% load custom_tags %}
	
	{% if not tag %}
		{% if sort != 'hot' %}
		<h2>New questions <a href="?{% url_replace request 'sort' 'hot' %}">Popular questions</a></h2>
	 	{% endif %}

	 	{% if sort == 'hot' %}
		<h2><a href="?{% url_replace request 'sort' 'date' %}">New questions </a>Popular questions</h2>
	 	{% endif %}
 	{% else %}
 	<h2>Tag: {{tag}}</h2>
 	{% endif %}

	{% for Question in question_page %}
		<div class = "question row">
			<div class = "span2">
				<div align="center">
					<img src="{{Question.author.avatar.url}}" class="img-polaroid" style="margin-top: 20px" width=100 heigth=100 alt=""/>
 				</div>   		
 				<div align="center">
					{{Question.author.user.username}}
				</div> 			
			</div>
			
			<div class = "span5">
				<a href="/question?id={{Question.id}}"> <h3>{{Question.title}}</h3> </a>
				<hr/>
				<div class="questiontext">
					<p>{{Question.text}}</p>
				</div>						
			</div>

			<div class="span2">
				<div align="center">
					<a class="btn btn-info js-like" href="" data-liketype="q" data-vote="-" data-id="{{Question.id}}" data-url="/like">-</a>
					<textarea readonly class="js_cnt" style="resize: none; width: 25px; height: 20px">{{Question.rating}}</textarea>					
					<a class="btn btn-info js-like" href="" data-liketype="q" data-vote="+" data-id="{{Question.id}}" data-url="/like">+</a>
				</div>   				
			</div>

			<div class="span5">				
			<p>{{Question.date_added}}</p>
			<p> 
			<a href="/question?id={{Question.id}}">Answer ({{Question.answer_set.count}})</a>
				<span style="margin-left: 5%;">
					{% if Question.tag_set.all %}	
					Tags:					
					{% for tag in Question.tag_set.all %} 
						<a href="/tag?tag={{tag.tag_word}}">{{tag.tag_word}} </a>
					{% endfor %}					
					{% endif %}
				</span>
			</p>		
			</div>
		</div>		
	{% endfor %}



	<div class="pagination">
		<ul>
			<li> <a href= "?{% url_replace request 'page' 1 %}">First</a> </li>
			<li>
			{% if question_page.has_previous %}
				<a href= "?{% url_replace request 'page' question_page.previous_page_number %}">Prev</a>
			{% endif %}	
			</li>
					
			{% for page in question_page.paginator.page_range %}
			{% if page < max_page and page > min_page %}
			<li class="{% if question_page.number == page %}active{% endif %} "> <a href="?{% url_replace request 'page' page %}"> {{page}} </a> </li>
			{% endif %}
			{% endfor %}

			<li>
			{% if question_page.has_next %}
				<a href= "?{% url_replace request 'page' question_page.next_page_number %}">Next</a>
			{% endif %}	
			</li>
			<li> <a href= "?{% url_replace request 'page' last_page_number %}">Last</a> </li>
		</ul>		
    </div>
	
{% endblock %}

{% block foot %}
<script type="text/javascript" src="{% static "my.js" %}"> </script>
{% endblock %}

templates/popular_tags.html
<h2>Popular tags</h2>		
{% for tag in popular_tags %}
<a style="font-size: 12pt;" href="/tag?tag={{tag.tag_word}}">{{tag.tag_word}}</a>
{% endfor %}

templates/profile.html
{% extends "base.html" %}
{% block content %}
<h2>Profile of {{user.username}}</h2>	
<br>
<form  action="" method="post" enctype="multipart/form-data"> 
{% csrf_token %}
	{% for field in user_form %}
	<div class="row">
		<div class="span2">
			<label for="{{ field.id_for_label }}">{{ field.label }}</label>
		</div>
		<div class="span5">
			<input id="{{ field.id_for_label }}" name="{{ field.name }}" type="text"			
			value="{{ field.value|default_if_none:"" }}"/>			
		</div>
	</div>
	{% if field.errors %}
		<div class="row">
			<div class="span2 offset2 alert alert-error"> 
				{{field.errors}}
			</div>
		</div>		
	{% endif %}

	{% endfor %}
	<div class="row">
		<div class="span2">
			<p>Rating</p>
		</div>
		<div class="span5">
				<label>{{user.profile.rating}}</label>				
		</div>
	</div>
	<div class="row">
		<div class="span2">
			<p>Upload avatar</p>
		</div>
		<div class="span5">
			<img class = "img" style = "margin-bottom: 15px" src="{{user.profile.avatar.url}}" heigth="100" width="100"/> 
			<div> {{profile_form.avatar}} </div>
		</div>
	</div>
	<br>
	<div class="row">
			<div class="span5 offset2">
					<input type="hidden" name="next" value="{{ next }}"/>
					<button type="submit" class="btn btn-info">Save changes</button>
			</div>
	</div>
</form>
{% endblock %}

templates/question.html
{% extends "base.html" %}


{% block content %}
	{% load staticfiles %}
	{% load custom_tags %}
	<h2>Question page</h2>
		<div class = "question row">
			<div class = "span2">
				<div align="center">
					<img src="{{Question.author.avatar.url}}" class="img-polaroid" style="margin-top: 20px" width=100 heigth=100 alt=""/>
 				</div>   		
 				<div align="center">
					{{Question.author.user.username}}
				</div> 			
			</div>

			<div class = "span5">
				<h3>{{Question.title}}</h3> 
				<hr/>
				<div class="questiontext">
					<p>{{Question.text}}</p>
				</div>						
			</div>

			<div class="span2">
				<div align="center">
					<a class="btn btn-info js-like" href="" data-liketype="q" data-vote="-" data-id="{{Question.id}}" data-url="/like">-</a>
					<textarea readonly class="js_cnt" style="resize: none; width: 25px; height: 20px">{{Question.rating}}</textarea>					
					<a class="btn btn-info js-like" href="" data-liketype="q" data-vote="+" data-id="{{Question.id}}" data-url="/like">+</a>
				</div>   				
			</div>

			<div class="span5">				
				<p>{{Question.date_added}}</p>
				<p> 
				{% if Question.tag_set.all %}	
						Tags:					
						{% for tag in Question.tag_set.all %} 
							<a href="/tag?tag={{tag.tag_word}}">{{tag.tag_word}} </a>
						{% endfor %}					
				{% endif %}
				</p>		
			</div>
		</div>
				
		<h3>Answers:</h3>
		{%for answer in answer_page %}
			<div class="question row">
				<div class = "span2">
					<div align="center">
						<img src="{{answer.author.avatar.url}}" class="img-polaroid" style="margin-top: 10px" width=50 heigth=50 alt=""/>
						<div align="center">
						{{answer.author.user.username}}
						</div>
	 				</div> 	 	
	 				<div align="center">
						<a class="btn btn-info js-like" href="" data-liketype="a" data-vote="-" data-id="{{answer.id}}" data-url="/like">-</a>
						<textarea readonly class="js_cnt" style="resize: none; width: 25px; height: 20px">{{answer.rating}}</textarea>					
						<a class="btn btn-info js-like" href="" data-liketype="a" data-vote="+" data-id="{{answer.id}}" data-url="/like">+</a>
					</div> 			 			
				</div>
				<div class = "span5">
					<p>{{answer.date_added}} 
					<b class="js_correct">{% if answer.is_right %} Correct answer  {% endif %}</b>
					</p> 
					<hr/>
					<div> <p>{{answer.text}}</p> </div>	
					<hr/>
					<p>
					{% if request.user == Question.author.user %}
						<input type="checkbox" class="js-isright" data-url="/rightanswer" 
						data-id ="{{answer.id}}" {% if  answer.is_right %} checked="checked" {% endif %}> Correct?<br>
					{% endif %}					
					</p>
				</div>							
			</div>
		{% endfor %}

	<div class="pagination">
		<ul>
			<li> <a href= "?{% url_replace request 'page' 1 %}">First</a></li>
			<li>
			{% if answer_page.has_previous %}
				<a href= "?{% url_replace request 'page' answer_page.previous_page_number %}">Prev</a>
			{% endif %}	
			</li>
			
			{% for page in answer_page.paginator.page_range %}
			{% if page < max_page and page > min_page %}
			<li class="{% if answer_page.number == page %}active{% endif %} "> <a href="?{% url_replace request 'page' page %}"> {{page}} </a> </li>
			{% endif %}
			{% endfor %}

			<li>
			{% if answer_page.has_next %}
				<a href= "?{% url_replace request 'page' answer_page.next_page_number %}">Next</a>
			{% endif %}	
			</li>
			<li> <a href= "?{% url_replace request 'page' last_page_number %}">Last</a> </li>
		</ul>
    </div>
    <hr>
    
    {% if user.is_authenticated %}
    <form method="POST" action="">
    {% csrf_token %}
    <div> 
    	<textarea  style="resize: none; width: 100%; height: 50px" name="{{ form.text.name }}"
    	type="text"></textarea> 
    </div>
	{% if form.text.errors %}
	<div class="alert alert-error"> 
				{{form.text.errors}}
			</div>		
	{% endif %}
	<input type="hidden" name="next" value="{{ next }}"/>
	<button type="submit" class="btn btn-primary">Answer!</button>
	<br>
    </form>
	{% endif %}

{% block foot %}
<script type="text/javascript" src="{% static "my.js" %}"> </script>
{% endblock %} 

{% endblock %}